### Xem version cua pandas


In [59]:
import pandas as pd
import numpy as np



print(pd.__version__)

2.3.3


4. Tạo một vector rỗng có kích thước 10 phần tử?


In [102]:
# Tao 1 vector rong
emArr = np.empty(10)
print(emArr.shape)  # xem kich thuoc mang

(10,)


5. Tạo một vector có các giá trị như sau: 26, 7, 19, 27, 12, 29.
   Sử dụng lệnh để cho biết số chiều và số phần tử của vector vừa tạo?


In [ ]:
a = np.array([26, 7, 19, 27, 12, 29.0])
a.ndim  # xem so chieu
a.shape  # xem kich thuoc

(6,)

6. Tạo một vector gồm 15 phần tử với các giá trị ngẫu nhiên từ 1-9?
   Cho biết giá trị của phần tử thứ 5 trong vector vừa tạo?


In [113]:
a = np.random.randint(1, 10, 15)  # randint(start,end,so phan tu)
print(a)
print(a[5])

[8 9 4 9 6 2 8 6 2 2 1 3 7 9 8]
2


7. Tạo một ma trận có kích thước 3x4, với các giá trị ngẫu nhiên.
   Cho biết chiều và số dòng, số cột của ma trận này?


In [115]:
a = np.random.randint(10, 30, (3, 4))
print(a)
print(a.ndim)  # imn ra chieu
a.shape  # in ra (3,4) la (so hang,so cot)

[[22 15 15 18]
 [25 17 17 28]
 [16 24 29 21]]
2


(3, 4)

8. Tạo một mảng có số dòng, số cột và các giá trị như sau:

- Cho biết số chiều, số dòng, số cột của mảng trên.
- Lấy tất cả giá trị của dòng 2 và dòng 3.
- Tạo một vector với các giá trị được lấy từ cột thứ 3.
- Tạo ra một ma trận mới với các giá trị được lấy từ ma trận trên
- Thay đổi giá trị 22 ở dòng 4, cột 2 thành giá trị 30


In [ ]:
a = np.array([[5, 10, 21], [11, 23, 18], [22, 19, 35], [96, 22, 26]])

a0 = np.ndim(a)
a1 = np.shape

print(a)

print(a[1:3, :])  # a[hang,cot]
# a[1:3,:]: tu hang 1 den hang 2, tat cac cot

print(a[1:4, 1:])

a[3, 1] = 30  # doi so 33 thanh 30
print(a)

[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 22 26]]
[[11 23 18]
 [22 19 35]]
[[23 18]
 [19 35]
 [22 26]]
[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 30 26]]


9. Tạo mảng 1 chiều với các giá trị từ 10 đến 20?

- Cho biết số lượng các phần tử có trong mảng?
- Biến đổi mảng 1 chiều trên thành mảng 2 chiều với kích thước 2x5?
- Cho biết số chiều của mảng vừa được biến đổi?


In [122]:
# 9
a = np.arange(10, 20)  # mang ma tu a den b thi su dung arange
print(a)
print(a.shape)

a2 = a.reshape(
    (2, 5)
)  # reshape: de bien doi mang 1 chieu thanh 2 chieu voi n hang va m cot
print(a2)
print(a2.ndim)

[10 11 12 13 14 15 16 17 18 19]
(10,)
[[10 11 12 13 14]
 [15 16 17 18 19]]
2


10. Tạo mảng 1 chiều với các giá trị như sau: 99, 46, 87, 62, 11, 32.

- Cho biết giá trị lớn nhất và nhỏ nhất của mảng trên?
- Sắp xếp mảng này theo tứ tự tăng dần?
- In ra các giá trị ở vị trí chẵn của mảng.
- Kiểm tra phần tử thứ 4 là giá trị chẵn hay lẻ. Xuất thông báo kết quả?
- Đếm số phần tử chẳn có trong mảng.
- Tìm giá trị trung bình (mean), giá trị trung vị (median), tổng?
- Thay đổi giá trị 87 bằng giá trị trung bình của mảng này?
- Xóa phần tử có giá trị 62 trong mảng?


In [98]:
a = np.array([99, 46, 87, 62, 11, 32])
print(np.max(a))

print(np.min(a))

print(np.sort(a))

for i in range(len(a)):
    if a[i] % 2 == 0:
        print(a[i])

print(np.mean(a))  # trung binh

print(np.median(sorted(a)))  # trung vi
# neu so phan tu le -> trung vi la so o giua
# neu so phan tu chan -> trung vi la trung binh cong 2 so o giua

print(np.sum(a))  # tong

a[a == 87] = np.mean(a)
print(a)

a2 = np.delete(a, np.where(a == 62))
print(a2)

99
11
[11 32 46 62 87 99]
46
62
32
56.166666666666664
54.0
337
[99 46 56 62 11 32]
[99 46 56 11 32]


11. Tạo một ma trận 3 chiều với các giá trị như sau:
    Ma trận 1:
    Ma trận 2:
    Ma trận 3:
    -> HìnhHình ma trân trên đề

- Truy xuất giá trị 2 dòng cuối của ma trận thứ nhất?
- Thay đổi các giá trị cột đầu tiên của ma trận thứ hai bằng giá trị trung bình của
  ma trận thứ nhất.
- Tính tổng giá trị của ma trận thứ ba.
- Thay đổi giá trị dòng cuối cùng của ma trận thứ 3 bằng -1.
- Tạo một ma trận mới từ ma trận thứ 2. Cho biết chiều của ma trận?
- Chuyển ma trận vừa tạo thành vector. Thêm vào cuối mảng giá trị 45?
- Thêm vào đầu mảng giá trị 99?
- Tạo một list các giá trị được lấy từ ma trận 3 chiều ban đầu.
